---
name: Publish library to pypi

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment:
      name: pypi
      url: https://pypi.org/p/aar-doc
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Install poetry
        run: pip install poetry

      - name: Build dist
        run: poetry build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247 # release/v1
